"""
Persistent Python execution sandbox for the agent.

Not a hardened security sandbox (it uses exec/eval) - this is meant to run in a
disposable environment you control (your own machine/VM), not to safely execute
untrusted third-party code from strangers. The Telegram messages that reach this
sandbox are the questions from the grading account, and the *code* it runs is
generated by your own LLM agent, not arbitrary user input.
"""

import ast
import contextlib
import io
import traceback


class PythonSandbox:
    """One instance per chat/conversation. State persists across .run() calls,
    like a REPL, so the agent can build a solution up over multiple steps."""

    def __init__(self):
        import pandas as pd
        import numpy as np
        import requests
        import json
        import math
        import re
        import io as _io
        import datetime
        import certifi
        import os as _os

        _os.environ.setdefault("SSL_CERT_FILE", certifi.where())
        _os.environ.setdefault("REQUESTS_CA_BUNDLE", certifi.where())

        self.globals = {
            "__builtins__": __builtins__,
            "pd": pd,
            "np": np,
            "requests": requests,
            "json": json,
            "math": math,
            "re": re,
            "io": _io,
            "datetime": datetime,
        }

    def run(self, code: str) -> dict:
        """Execute code. If the last line is a bare expression, its value is
        captured (like a REPL) and also stashed in `_` for later use."""
        stdout = io.StringIO()
        stderr = io.StringIO()
        result_repr = None

        try:
            parsed = ast.parse(code, mode="exec")
        except SyntaxError as e:
            return {"stdout": "", "stderr": f"SyntaxError: {e}", "result": None}

        last_expr = None
        if parsed.body and isinstance(parsed.body[-1], ast.Expr):
            last_expr = ast.Expression(parsed.body.pop().value)

        try:
            with contextlib.redirect_stdout(stdout), contextlib.redirect_stderr(stderr):
                exec(compile(parsed, "<agent>", "exec"), self.globals)
                if last_expr is not None:
                    value = eval(compile(last_expr, "<agent>", "eval"), self.globals)
                    self.globals["_"] = value
                    result_repr = repr(value)
        except Exception:
            stderr.write(traceback.format_exc())

        return {
            "stdout": stdout.getvalue()[-4000:],
            "stderr": stderr.getvalue()[-4000:],
            "result": result_repr,
        }