"""
Persistent Python execution sandbox for the agent.

Not a hardened security sandbox (it uses exec/eval) - this is meant to run in a
disposable environment you control (your own machine/VM), not to safely execute
untrusted third-party code from strangers. The Telegram messages that reach this
sandbox are the questions from the grading account, and the *code* it runs is
generated by your own LLM agent, not arbitrary user input.
"""

import ast
import contextlib
import io
import traceback


class PythonSandbox:
    """One instance per chat/conversation. State persists across .run() calls,
    like a REPL, so the agent can build a solution up over multiple steps."""

    def __init__(self):
        import pandas as pd
        import numpy as np
        import requests
        import json
        import math
        import re
        import io as _io
        import datetime
        import urllib3
        import pdfplumber

        DEFAULT_HEADERS = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)"}

        def fetch_url(url, **kwargs):
            """GET a URL with a browser-like User-Agent (some sites, like
            Wikipedia, reject requests without one), retrying with SSL
            verification disabled if the site has a broken certificate chain
            (common on some .gov.in sites - a server-side issue no client
            fix can solve)."""
            headers = {**DEFAULT_HEADERS, **kwargs.pop("headers", {})}
            try:
                return requests.get(url, timeout=30, headers=headers, **kwargs)
            except requests.exceptions.SSLError:
                urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)
                return requests.get(url, timeout=30, headers=headers, verify=False, **kwargs)

           

        def extract_pdf_text(url):
            """Download a PDF and extract its text, page by page, using
            pdfplumber. Returns a single string with all pages concatenated
            (page breaks marked). Use this instead of pd.read_pdf (doesn't
            exist) or PyPDF2 (not installed) for any PDF source."""
            resp = fetch_url(url)
            resp.raise_for_status()
            text_parts = []
            with pdfplumber.open(_io.BytesIO(resp.content)) as pdf:
                for i, page in enumerate(pdf.pages):
                    page_text = page.extract_text() or ""
                    text_parts.append(f"--- page {i + 1} ---\n{page_text}")
            return "\n".join(text_parts)

        def fetch_wikipedia_tables(url):
                    """Fetch a Wikipedia page and return all its tables as a list of
                    DataFrames. Handles the browser User-Agent Wikipedia requires
                    automatically - use this instead of pd.read_html(url) directly,
                    which will get a 403 Forbidden without the right headers."""
                    resp = fetch_url(url)
                    resp.raise_for_status()
                    return pd.read_html(_io.StringIO(resp.text)) 

        self.globals = {
            "__builtins__": __builtins__,
            "pd": pd,
            "np": np,
            "requests": requests,
            "fetch_url": fetch_url,
            "extract_pdf_text": extract_pdf_text,
            "fetch_wikipedia_tables": fetch_wikipedia_tables,
            "json": json,
            "math": math,
            "re": re,
            "io": _io,
            "datetime": datetime,
        }

    def run(self, code: str) -> dict:
        """Execute code. If the last line is a bare expression, its value is
        captured (like a REPL) and also stashed in `_` for later use."""
        stdout = io.StringIO()
        stderr = io.StringIO()
        result_repr = None

        try:
            parsed = ast.parse(code, mode="exec")
        except SyntaxError as e:
            return {"stdout": "", "stderr": f"SyntaxError: {e}", "result": None}

        last_expr = None
        if parsed.body and isinstance(parsed.body[-1], ast.Expr):
            last_expr = ast.Expression(parsed.body.pop().value)

        try:
            with contextlib.redirect_stdout(stdout), contextlib.redirect_stderr(stderr):
                exec(compile(parsed, "<agent>", "exec"), self.globals)
                if last_expr is not None:
                    value = eval(compile(last_expr, "<agent>", "eval"), self.globals)
                    self.globals["_"] = value
                    result_repr = repr(value)
        except Exception:
            stderr.write(traceback.format_exc())

        return {
            "stdout": stdout.getvalue()[-4000:],
            "stderr": stderr.getvalue()[-4000:],
            "result": result_repr,
        }